# IP addresses used by VPN
[ip]
src='10.7.0.1'
dst='10.7.0.2'

# If CPU isolation is used
[isolation]
priority=99
isolate_send=true  # Thread that sends the pattern, the most important to isolate
core_send=2
isolate_obfuscate=true
core_obfuscate=3
isolate_deobfuscate=false
core_deobfuscate=4

# Interfaces to send and receive on
# To move away from command line arguments
[interface]
no_obf='veth_d'
obf='wg3'
# The source device to obfuscate from. We will only obfuscate frames that have src mac equal to the mac of this device
# Could be a router or a device on the LAN
src_device='vethd' 

#Other parameters
[general]
rate=200.0
pad_log_interval=2e3
save=false 
local=false
log=true
hw_obfuscation=false
backbone=true
