[package]
name = "sender_receiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.34"
rand = "0.8.4"
libc = "0.2.107"
toml = "0.8.12"
csv = "1.3.0"
crossbeam = "0.8"
