# IP addresses used by VPN
[ip]
src='10.7.0.2'
dst='10.7.0.3'

# If CPU isolation is used
# Core number don't matter if no isolation
[isolation]
priority=99
isolate_sender=false 
core_sender=0
isolate_receiver=false
core_receiver=1

[interface]
input='ens38'
output='ens38'

#Other parameters
[general]
rate=100.0
time=15.0 #In sec
save=false
send=true
receive=false
log=true
dataset='caida'
min_pkt_length=0
max_pkt_length=0
